// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	pa "github.com/Lambels/patrickarvatu.com"
	mock "github.com/stretchr/testify/mock"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: ctx, blog
func (_m *CommentService) CreateComment(ctx context.Context, blog *pa.Comment) error {
	ret := _m.Called(ctx, blog)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pa.Comment) error); ok {
		r0 = rf(ctx, blog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, id
func (_m *CommentService) DeleteComment(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindCommentByID provides a mock function with given fields: ctx, id
func (_m *CommentService) FindCommentByID(ctx context.Context, id int) (*pa.Comment, error) {
	ret := _m.Called(ctx, id)

	var r0 *pa.Comment
	if rf, ok := ret.Get(0).(func(context.Context, int) *pa.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pa.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindComments provides a mock function with given fields: ctx, filter
func (_m *CommentService) FindComments(ctx context.Context, filter pa.CommentFilter) ([]*pa.Comment, int, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*pa.Comment
	if rf, ok := ret.Get(0).(func(context.Context, pa.CommentFilter) []*pa.Comment); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pa.Comment)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, pa.CommentFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, pa.CommentFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateComment provides a mock function with given fields: ctx, update
func (_m *CommentService) UpdateComment(ctx context.Context, update pa.CommentUpdate) (*pa.Comment, error) {
	ret := _m.Called(ctx, update)

	var r0 *pa.Comment
	if rf, ok := ret.Get(0).(func(context.Context, pa.CommentUpdate) *pa.Comment); ok {
		r0 = rf(ctx, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pa.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, pa.CommentUpdate) error); ok {
		r1 = rf(ctx, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
