// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: to, body, subject
func (_m *EmailService) SendEmail(to []string, body string, subject string) error {
	ret := _m.Called(to, body, subject)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string, string) error); ok {
		r0 = rf(to, body, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
