// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	pa "github.com/Lambels/patrickarvatu.com"
	mock "github.com/stretchr/testify/mock"
)

// EventService is an autogenerated mock type for the EventService type
type EventService struct {
	mock.Mock
}

// Push provides a mock function with given fields: ctx, event
func (_m *EventService) Push(ctx context.Context, event pa.Event) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pa.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterHandler provides a mock function with given fields: topic, handler
func (_m *EventService) RegisterHandler(topic string, handler pa.EventHandler) {
	_m.Called(topic, handler)
}
