// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Payload is an autogenerated mock type for the Payload type
type Payload struct {
	mock.Mock
}
