// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	pa "github.com/Lambels/patrickarvatu.com"
	mock "github.com/stretchr/testify/mock"
)

// SubBlogService is an autogenerated mock type for the SubBlogService type
type SubBlogService struct {
	mock.Mock
}

// CreateSubBlog provides a mock function with given fields: ctx, blog
func (_m *SubBlogService) CreateSubBlog(ctx context.Context, blog *pa.SubBlog) error {
	ret := _m.Called(ctx, blog)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pa.SubBlog) error); ok {
		r0 = rf(ctx, blog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSubBlog provides a mock function with given fields: ctx, id
func (_m *SubBlogService) DeleteSubBlog(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindSubBlogByID provides a mock function with given fields: ctx, id
func (_m *SubBlogService) FindSubBlogByID(ctx context.Context, id int) (*pa.Blog, error) {
	ret := _m.Called(ctx, id)

	var r0 *pa.Blog
	if rf, ok := ret.Get(0).(func(context.Context, int) *pa.Blog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pa.Blog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSubBlogs provides a mock function with given fields: ctx, filter
func (_m *SubBlogService) FindSubBlogs(ctx context.Context, filter pa.SubBlogFilter) ([]*pa.Blog, int, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*pa.Blog
	if rf, ok := ret.Get(0).(func(context.Context, pa.SubBlogFilter) []*pa.Blog); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pa.Blog)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, pa.SubBlogFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, pa.SubBlogFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateSubBlog provides a mock function with given fields: ctx, update
func (_m *SubBlogService) UpdateSubBlog(ctx context.Context, update pa.SubBlogUpdate) (*pa.Blog, error) {
	ret := _m.Called(ctx, update)

	var r0 *pa.Blog
	if rf, ok := ret.Get(0).(func(context.Context, pa.SubBlogUpdate) *pa.Blog); ok {
		r0 = rf(ctx, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pa.Blog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, pa.SubBlogUpdate) error); ok {
		r1 = rf(ctx, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
